CREATE TABLE IF NOT EXISTS RECIPES(
    id IDENTITY PRIMARY KEY,
    name VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS INGREDIENTS (
    id IDENTITY PRIMARY KEY,
    name VARCHAR(128),
    recipe_id INT8
);

CREATE TABLE IF NOT EXISTS RECIPE_INGREDIENTS (
    recipe_id INT8,
    ingredient_id INT8,
    amount INT
);